### ISSUE TITLE
 Use Undertow as Embedded Server with Red Hat Fuse

### ISSUE THREAD

**Issue by osmman** [RHsyseng/IntegrationApp-Automation#27]
Tomcat is not officially supported by Red Hat Fuse as an embedded server. Instead, you should use Undertow as a web server.

Look at [this](https://github.com/fabric8-quickstarts/spring-boot-camel-rest-3scale/blob/spring-boot-camel-rest-3scale-1.0.0.fuse-740017-redhat-00002/pom.xml#L58-L71) Fuse quickstart. It contains the correct configuration.

**Comment by redhatHameed** [comment]
@osmman Fix in PR- https://github.com/rh-integration/IntegrationApp-Automation/pull/37
could you please have a look on that, also fixed the issues- 28/29/34/35/36.
