### ISSUE TITLE
Don't use deprecated BOM for Red Hat Fuse projects

### ISSUE THREAD

**Issue by osmman** [RHsyseng/IntegrationApp-Automation#28]
Please don't use `fabric8-project-bom-camel-spring-boot` BOM in fuse-alert-service and fuse-user-service projects. This BOM is deprecated for use by the customer because it contains only a subset of Fuse dependencies.

You should use `org.jboss.redhat-fuse:fuse-springboot-bom`.
See https://github.com/fabric8-quickstarts/spring-boot-camel-rest-3scale/blob/spring-boot-camel-rest-3scale-1.0.0.fuse-740017-redhat-00002/pom.xml#L44-L49

**Comment by redhatHameed** [comment]
@osmman Fixed in PR https://github.com/rh-integration/IntegrationApp-Automation/pull/37, could you please have a look

**Comment by osmman** [comment]
LGTM, thanks.
