### ISSUE TITLE
Use productized maven plugins in Red Hat Fuse projects

### ISSUE THREAD

**Issue by osmman** [RHsyseng/IntegrationApp-Automation#29]
Red Hat Fuse repackages [many](https://github.com/jboss-fuse/redhat-fuse/tree/redhat-fuse-7.4.0.fuse-740036/fuse-maven-plugins) maven plugins and they should be preferred. The advantage of using these productized plugins is that they are tested and versions are aligned with the product.

**org.jboss.redhat-fuse:fabric8-maven-plugin**
https://github.com/fabric8-quickstarts/spring-boot-camel-rest-3scale/blob/spring-boot-camel-rest-3scale-1.0.0.fuse-740017-redhat-00002/pom.xml#L157-L158

**org.jboss.redhat-fuse:spring-boot-maven-plugin**
https://github.com/fabric8-quickstarts/spring-boot-camel-rest-3scale/blob/spring-boot-camel-rest-3scale-1.0.0.fuse-740017-redhat-00002/pom.xml#L144-L145

**Comment by redhatHameed** [comment]
@osmman Fixed in PR https://github.com/rh-integration/IntegrationApp-Automation/pull/37, could you please have a look

**Comment by osmman** [comment]
LGTM, thanks.
