### ISSUE TITLE
wrong mapping rule in API created by aggregated-pipeline

### ISSUE THREAD

**Issue by mkudlej** [RHsyseng/IntegrationApp-Automation#30]
I've run ```aggregated-pipeline``` and there is new API managed by 3scale. It has mapping rule ```/cicd/maingateway/profile/{id}$``` which is wrong because there is endpoint defined in Fuse as ```cicd/users/profile/{id}```.
It can be solved by one of these options:
1) define same mapping rule in Fuse and API managed by 3scale
2) setup ```URL rewriting``` policy to rewrite url before applying mapping rules

**Comment by redhatHameed** [comment]
> I've run `aggregated-pipeline` and there is new API managed by 3scale. It has mapping rule `/cicd/maingateway/profile/{id}$` which is wrong because there is endpoint defined in Fuse as `cicd/users/profile/{id}`.
> It can be solved by one of these options:
> 
> 1. define same mapping rule in Fuse and API managed by 3scale
> 2. setup `URL rewriting` policy to rewrite url before applying mapping rules

The mapping rule `/cicd/maingateway/profile/{id}$` is correct- it uses maingateway service url endpoint

There are three fuse services deployed by Jenkins pipeline 
1- user service, 2- alert service, 3- maingateway service 
The main gateway service integrates, the service 1&2.
The complete URL to hit maingateway service is - 
```http://maingatewayservice-route/profile/11111?alertType=ACCIDENT```

**Comment by mkudlej** [comment]
yes you're right, I'll close this issue.
