### ISSUE TITLE
Convert body to string is unnecessary before unmarshal step

### ISSUE THREAD

**Issue by osmman** [RHsyseng/IntegrationApp-Automation#35]
Please remove transformation of body to String in maingateway camel route. This transformation is unnecessary because unmarshal consume data of `InputStream` type. 

```xml
<convertBodyTo id="_convertBodyTo1" type="java.lang.String"/>
<unmarshal id="_unmarshal1">
    <json library="Jackson"/>
</unmarshal>
```

**Comment by redhatHameed** [comment]
@osmman Fix in PR https://github.com/rh-integration/IntegrationApp-Automation/pull/37, could you please have a look

**Comment by osmman** [comment]
LGTM, thanks.
