### ISSUE TITLE
Fuse applications expose two paths of API Doc

### ISSUE THREAD

**Issue by osmman** [RHsyseng/IntegrationApp-Automation#36]
Fuse applications have incorrectly defined API Doc paths. The problem is that REST configuration is set to expose API Doc at `/openapi.json` path but you expose the API Doc on `/openapi-spec.json`.

This causes the application creates both paths:
`/cicd/openapi.json` - Returns 200 and empty response
`/cicd/openapi-spec.json`

```xml
<restConfiguration apiContextPath="/openapi.json"/>
<rest path="/">
    <get produces="application/json" uri="openapi-spec.json">
```

**Comment by redhatHameed** [comment]
@osmman Fix in PR https://github.com/rh-integration/IntegrationApp-Automation/pull/37, could you please have a look

**Comment by osmman** [comment]
LGTM, thanks.
