### ISSUE TITLE
Eliminate 10 minute wait time for building all modules

### ISSUE THREAD

**Issue by bmozaffa** [RHsyseng/IntegrationApp-Automation#5]
Running the aggregator pipeline currently prompts user input as to whether all projects should be built and deployed. This precludes it from running in the OpenShift console, resulting in the need for a 10 minute pause in case the user logs in to Jenkins to make the selection. The current default is to build all modules after 10 minutes, if no user feedback is received.

Suggestion is to try and introduce a checkbox by default, that is turned on by default, to build all modules. Users building through the Jenkins console can then uncheck this "build all" option and will be prompted for the project to build and deploy. Those using the OpenShift console will simply build all modules without any delay.

**Comment by myeung18** [comment]
Should I assume this means that if the pipelines're triggered through Openshift console,  build and deployment will be done as a whole. No extra prompt will be given before deploying to production as well?

If the pipelines's are triggered through Jenkins, by default it is still build and deploy all, but before a user starts the job, he can customize whether to build all or not. We still don't need second prompt for production deployment?

Lastly, I found that adding a checkbox doesn't seem to be necessary.  As in Jenkins, when user click on the job to start, the submit page already have all the parameters listed and user can customize everything there. E.g. key in 'all' in the DEPLOY_MODULE field to build all, key in 'fisuser' to build just a particular module.

**Comment by bmozaffa** [comment]
> Should I assume this means that if the pipelines're triggered through Openshift console, build and deployment will be done as a whole. No extra prompt will be given before deploying to production as well?

Hmm, good point. I think we should default to not deploying to production.

> If the pipelines's are triggered through Jenkins, by default it is still build and deploy all, but before a user starts the job, he can customize whether to build all or not. We still don't need second prompt for production deployment?

I would say another checkbox for deploying to production, instead of the current user input, should fix this, no? It would be unchecked by default and not deploy to prod, but can be selected from Jenkins.

> Lastly, I found that adding a checkbox doesn't seem to be necessary. As in Jenkins, when user click on the job to start, the submit page already have all the parameters listed and user can customize everything there. E.g. key in 'all' in the DEPLOY_MODULE field to build all, key in 'fisuser' to build just a particular module.

But that would mean not being able to use the nice user input prompt, no?

**Comment by myeung18** [comment]
I think the nice user input prompt happens during the pipeline runtime.

To sum up:
For the build (including deploy to dev/test), by default, during the pipeline runtime, no matter it is in OpenShift or Jenkins, no prompt.  But if runs from Jenkins, user can uncheck the box saying I want to be prompted during the runtime to allow me to do selective build.  

For the deployment to production, runtime behaviors are the same for both environment, and by default, show prompt.  But if runs from Jenkins, user can uncheck/check the box to determine whether he wants to be prompted to deploy to production or not during the pipeline runtime.

btw, Openshift will actually see the job started from Jenkins as well as they are in sync.

**Comment by bmozaffa** [comment]
> I think the nice user input prompt happens during the pipeline runtime.
> 
> To sum up:
> For the build (including deploy to dev/test), by default, during the pipeline runtime, no matter it is in OpenShift or Jenkins, no prompt. But if runs from Jenkins, user can uncheck the box saying I want to be prompted during the runtime to allow me to do selective build.

All good up to here

> For the deployment to production, runtime behaviors are the same for both environment, and by default, show prompt.

Not sure about this part. So if running from OpenShift, there will be a prompt to deploy to production that the user won't see? What will the impact be? Will it just sit there for a long time and eventually time out? I was thinking it would not deploy to prod and successfully complete right away.

> But if runs from Jenkins, user can uncheck/check the box to determine whether he wants to be prompted to deploy to production or not during the pipeline runtime.

What's the prompt? What is the default checkbox state? Would they check it, just to confirm again that they want to deploy to production? Wouldn't that be redundant?

> 
> btw, Openshift will actually see the job started from Jenkins as well as they are in sync.

**Comment by myeung18** [comment]
Not sure about this part. So if running from OpenShift, there will be a prompt to deploy to production that the user won't see? What will the impact be? Will it just sit there for a long time and eventually time out? I was thinking it would not deploy to prod and successfully complete right away.

 --Oh, you mean, no production deployment by default.  It can only be activated through Jenkins console by checking that box.  I misread.  Yes, we can do it.

What's the prompt? What is the default checkbox state? Would they check it, just to confirm again that they want to deploy to production? Wouldn't that be redundant?

-- Yup, since all the parameter are listed there already in Jenkins, adding any check box really do seem to be unnecessary.  User just need to do change any value in the default text field to twist the runtime behavior.

May be I should show you with share screen tomorrow.

**Comment by myeung18** [comment]
Changes are done.

By default. build all and deploy all to dev and test, no production deployment.

Customize through Jenkins:
User can check the 'SELECT_BUILD_MODULE' box to allow them to see menu prompt to select one or all modules to build.  If user also check 'SELECT_DEPLOY_TO_PROD" box, then after the build, an additional prompt will be shown to ask user if he/she approves his/her previous build to promote to production.
If SELECT_BUILD_MODULE is uncheck, pipeline disregards SELECT_DEPLOY_TO_PROD's value, no approval to production prompt will be shown, and no promotion to production.

Select Module Prompt wait time: 3 mins
Approve to Promote : 2 Hours
